# Generated by Django 3.2 on 2023-07-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('middle_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('annual_salary', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('email_id', models.CharField(max_length=20)),
                ('pin_code', models.IntegerField()),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
