# Generated by Django 3.2 on 2023-07-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
